### ISSUE TITLE
Possible bug while testing on raspberry pi (better tests needed)

### ISSUE THREAD

**Issue by nbari** [epazote/epazote#2]
When  compiling for a raspberry pi 1:

```
env GOOS=freebsd GOARCH=arm GOARM=6 go build -o epazote cmd/epazote/main.go 
```

If the service goes down a notification is sent, after the service come up, a notifications  is also  sent, so far so good, this is the expected behaviour,  but for subsequent requests a notification is always sent,  this should only happen once since a notification is sent every 5 seconds (for example below)

After compiling/uploading binary for the  second time this issue didn't happened again, therefore more tests needs to be done to ensure is properly working

```
services:
    google:
        url: https://test-server.example.com
        seconds: 5
        expect:
            status: 302
            ssl:
                hours: 72
            if_not:
                cmd: echo -n "google down"
                notify: yes
```
