### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by nbari** [epazote/epazote#3]
Verify service xxxx options: "runtime error" index out of range"

having this on a Raspberry PI 1 (GOARM=6)

**Comment by aaronarduino** [comment]
@nbari I'm interested in helping fix this bug. What was the .yml file contents when this happened?

**Comment by nbari** [comment]
@aaronarduino thanks in advance, this is the .yml I was using for testing:

```
config:
    smtp:
        username: username@doman.tld
        password: secret
        server: smtp.gmail.com
        port: 587
        headers:
            from: monitor@domain.tld
            to: usr@domain.tld
            subject: "[_name_,  _because_]"

services:
    sign.io:
        url: https://www.sign.io/
        seconds: 30
        threshold:
            healthy: 2
            unhealthy: 2
        expect:
            ssl:
                hours: 72
            status: 200
            header:
                X-Xrds-Location: http://www.sign.io/xrds
            if_not:
                notify: yes

    site2:
        url: http://example.com/
        seconds: 30
        threshold:
            healthy: 2
            unhealthy: 2
        expect:
            ssl:
                hours: 72
            status: 200
            if_not:
                notify: yes
```
