### ISSUE TITLE
if body containx X do something

### ISSUE THREAD

**Issue by nbari** [epazote/epazote#7]
When using cloudflare if page is unavailable a web page is present with a 520 code.

having something like

```
if_body: any string
   action: xxxxx
```

could be useful

**Comment by nbari** [comment]
fixed with:

```yaml
---
services:
  test:
    url: {}/test
    every: 30s
    expect:
      status: 200
      body: <string>
```

if body starts with `r"` is a regex, by default is `r".*{}.*"`
